// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// matchDate
IntegerVector matchDate(IntegerVector refSeries, IntegerVector tsSeries, int validDays, int lag, bool nextIfNotFound);
RcppExport SEXP _RcppFun_matchDate(SEXP refSeriesSEXP, SEXP tsSeriesSEXP, SEXP validDaysSEXP, SEXP lagSEXP, SEXP nextIfNotFoundSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type refSeries(refSeriesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type tsSeries(tsSeriesSEXP);
    Rcpp::traits::input_parameter< int >::type validDays(validDaysSEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< bool >::type nextIfNotFound(nextIfNotFoundSEXP);
    rcpp_result_gen = Rcpp::wrap(matchDate(refSeries, tsSeries, validDays, lag, nextIfNotFound));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RcppFun_matchDate", (DL_FUNC) &_RcppFun_matchDate, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_RcppFun(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
