// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// matchDate
IntegerVector matchDate(IntegerVector refSeries, IntegerVector tsSeries, int validDays, int lag);
RcppExport SEXP RcppFun_matchDate(SEXP refSeriesSEXP, SEXP tsSeriesSEXP, SEXP validDaysSEXP, SEXP lagSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type refSeries(refSeriesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type tsSeries(tsSeriesSEXP);
    Rcpp::traits::input_parameter< int >::type validDays(validDaysSEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    __result = Rcpp::wrap(matchDate(refSeries, tsSeries, validDays, lag));
    return __result;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP RcppFun_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(rcpp_hello_world());
    return __result;
END_RCPP
}
