// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// matchDate
IntegerVector matchDate(IntegerVector refSeries, IntegerVector tsSeries, int validDays, int lag);
RcppExport SEXP RcppFun_matchDate(SEXP refSeriesSEXP, SEXP tsSeriesSEXP, SEXP validDaysSEXP, SEXP lagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type refSeries(refSeriesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type tsSeries(tsSeriesSEXP);
    Rcpp::traits::input_parameter< int >::type validDays(validDaysSEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    rcpp_result_gen = Rcpp::wrap(matchDate(refSeries, tsSeries, validDays, lag));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP RcppFun_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}
