# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matchDate <- function(refSeries, tsSeries, validDays, lag, nextIfNotFound = FALSE) {
    .Call('_RcppFun_matchDate', PACKAGE = 'RcppFun', refSeries, tsSeries, validDays, lag, nextIfNotFound)
}

