# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matchDate <- function(refSeries, tsSeries, validDays, lag) {
    .Call('RcppFun_matchDate', PACKAGE = 'RcppFun', refSeries, tsSeries, validDays, lag)
}

rcpp_hello_world <- function() {
    .Call('RcppFun_rcpp_hello_world', PACKAGE = 'RcppFun')
}

